### ISSUE TITLE
API calls fail for Rails apps that respond to HTML and JSON

### ISSUE THREAD

**Issue by unikitty37** [victor-am/rails-ranger#25]
Given the following controller:

```ruby
class ThingController < ApplicationController
  def index
    @things = Things.all
    respond_to do |format|
      format.html
      format.json { render json: @things }
    end
  end
```

and the following JavaScript:

```js
api.list('things').then((response) => {
  console.log(response.data)
})
```

then `response.data` contains the HTML of `/things` rather JSON. If I visit `/things.json` in the browser I get the expected JSON.

I can't see how to configure rails-ranger or axios to append `.json` to the URL. Is this possible? Sadly, calling `api.list('things.json')` produces a request to `things_json`, which doesn't help much.

(I realise that rails-ranger's really intended for use with API-only Rails backends, but it would be extremely useful to be able to have it work for this case, even if that's not the default behaviour, as we don't always have control over the other end…)

Thanks!

**Comment by victor-am** [comment]
**Edit:** nevermind my last answer, there is a simple way to solve this:

You can add the following to your setup to make Rails always respond with json:

```js
import RailsRanger from 'rails-ranger'

const config = {
  axios: {
    baseURL: 'http://api.myapp.com',
    headers: {
      'Content-Type': 'application/json'
      'Accept': 'application/json'
    }
  }
}

export default new RailsRanger(config)
```

Does this solve the problem? 😄

**Comment by unikitty37** [comment]
That's done the job — thanks!

Is it worth adding this to the README?

**Comment by victor-am** [comment]
Absolutely!
Gonna re-open this just as a reminder to add it to the README later.

Thanks a lot 😄

**Comment by victor-am** [comment]
Done in 82a71be813e0c87421fdf51827400f25a11f17bd
