### ISSUE TITLE
this.client is undefined in readme example

### ISSUE THREAD

**Issue by ryanmk54** [victor-am/rails-ranger#39]
I am trying to copy the [example in the readme](https://github.com/victor-am/rails-ranger#build-your-own-client-object), with the following code, but I get the error: this.client is undefined. If I change `this.client` to `client` it works fine.

```
import RailsRanger from 'rails-ranger';
const client = new RailsRanger;
export default {
  client,

  orders: {
    update(params) {
      return this.client.update('orders', params) // <-- error on this line
        .then(response => response.data)
    } 
  }
};
```

**Comment by victor-am** [comment]
Hi @ryanmk54 , thanks for pointing it out!
It should be fixed on b0e1c02616275cb3e8541bf69e22c8c221b06c05 😄
