### ISSUE TITLE
Upgrade axios dependency to 0.21.1

### ISSUE THREAD

**Issue by ryanmk54** [victor-am/rails-ranger#44]
When running yarn install, I see the following warning
warning rails-ranger > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see [https://github.com/axios/axios/pull/3410](https://github.com/axios/axios/pull/3410)

**Comment by victor-am** [comment]
Oh, good call!
I will try to get into it at some point in the next week but if you need it fast and feel like opening a pull request be my guest 😄 
I believe the API should be the same, so probably just bumping the lib and running the tests should be enough.

**Comment by valdemarua** [comment]
Hey @victor-am 
Here is PR: https://github.com/victor-am/rails-ranger/pull/45

**Comment by victor-am** [comment]
Just published the version 1.2.1 of the library with a couple of version bumps (2 of them in non-dev dependencies: axios and lodash). More info about the release here: https://github.com/victor-am/rails-ranger/releases/tag/1.2.1

Thanks for the help guys 😄
